# uranium_project\uranium_app\urls.py

from django.urls import path
from .views import (
    HomeAPIView,
    NewsAPIView,
    NewsDetailAPIView,
    CalDataAPIView,
    WorldNuclearDataAPIView,
    StocksAPIView,
    GetTopPerformingStocksAPIView,
    AboutAPIView,
    GlossaryAPIView,
    EssentialsView,
    ContactView,
    ForumAPIView,
    CreatePostAPIView,
    PostDetailAPIView,
    LoginAPIView,
    RegisterAPIView,
    ProfileView,
    SubscribeAPIView,
    SubscriptionListAPIView,
    SendEmailAPIView,
    UpdateAvatarAPIView,
    DeleteAvatarAPIView,
    UserLogoutAPIView,
    SearchQuestionsAPIView,
    GetUraniumYoutubeVideos,
    MiningComNewsAPIView,
    WorldNuclearNewsAPIView,
    MiningTechnologyNewsAPIView,
    InformKZNewsAPIView,
    StockNewsAPIView,
    ArticleContentAPIView,
    IAEANewsAPIView,
    NorthernMinerNewsAPIView,
    NucNetNewsAPIView
)

urlpatterns = [
    path('home/', HomeAPIView.as_view(), name='home'),
    path('news/', NewsAPIView.as_view(), name='news'),
    path('news/<int:article_id>/', NewsDetailAPIView.as_view(), name='news_detail'),
    path('calendar/', CalDataAPIView.as_view(), name='calendar'),
    path('nuclear-data/', WorldNuclearDataAPIView.as_view(), name='nuclear_data'),
    path('stocks/', StocksAPIView.as_view(), name='stocks'),
    path('stocks/top-performing/', GetTopPerformingStocksAPIView.as_view(), name='top_performing_stocks'),
    path('about/', AboutAPIView.as_view(), name='about'),
    path('glossary/', GlossaryAPIView.as_view(), name='glossary'),
    path('essentials/', EssentialsView.as_view(), name='essentials'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('forum/', ForumAPIView.as_view(), name='forum'),
    path('forum/create/', CreatePostAPIView.as_view(), name='create_post'),
    path('forum/<int:post_id>/', PostDetailAPIView.as_view(), name='post_detail'),
    path('register/', RegisterAPIView.as_view(), name='register'),
    path('login/', LoginAPIView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('subscribe/', SubscribeAPIView.as_view(), name='subscribe'),
    path('subscriptions/', SubscriptionListAPIView.as_view(), name='subscription_list'),
    path('send-email/', SendEmailAPIView.as_view(), name='send_email'),
    path('avatar/update/', UpdateAvatarAPIView.as_view(), name='update_avatar'),
    path('avatar/delete/', DeleteAvatarAPIView.as_view(), name='delete_avatar'),
    path('logout/', UserLogoutAPIView.as_view(), name='logout'),
    path('search-questions/', SearchQuestionsAPIView.as_view(), name='search_questions'),
    path('youtube-videos/', GetUraniumYoutubeVideos.as_view(), name='get_youtube_videos'),
    path('news/mining-com/', MiningComNewsAPIView.as_view(), name='mining_com_news'),
    path('news/world-nuclear-news/', WorldNuclearNewsAPIView.as_view(), name='world_nuclear_news'),
    path('news/mining-technology/', MiningTechnologyNewsAPIView.as_view(), name='mining_technology_news'),
    path('news/inform-kz/', InformKZNewsAPIView.as_view(), name='inform_kz_news'),
    path('news/stock-news/', StockNewsAPIView.as_view(), name='stock_news'),
    path('news/iaea/', IAEANewsAPIView.as_view(), name='iaea_news'),
    path('news/northern-miner/', NorthernMinerNewsAPIView.as_view(), name='northern_miner_news'),
    path('news/nucnet/', NucNetNewsAPIView.as_view(), name="nucnet_news"),
    path('news/<str:article_id>/', NewsDetailAPIView.as_view(), name='news_detail'),
    path('article-content/<str:article_id>/', ArticleContentAPIView.as_view(), name='article_content')
]